### ISSUE TITLE
CKR_CRYPTOKI_NOT_INITIALIZED - AWS CloudHSM

### ISSUE THREAD

**Issue by ghost** [bentonstark/pihsm#13]
Benton - I have been playing with your library and stuck on open_session. I am using it with AWS CloudHSM and the SDK 3. I have managed to create an HsmClient, using:

`c = HsmClient(pkcs11_lib="/opt/cloudhsm/lib/libcloudhsm_pkcs11.so")`

But, everything else returns a:

'open_session: PKCS#11 C_OpenSession on slot 1 failed with return value 400. CKR_CRYPTOKI_NOT_INITIALIZED (0x00000190)'

Not clear if I am missing a step or if there is an issue on the AWS side. Any thoughts would be greatly appreciated.

Thanks,

Kyle

**Comment by bentonstark** [comment]
Have you confirmed the hsm is accessible using other tools?

**Comment by ghost** [comment]
OK, that solved that problem. For anyone else who might come across this. I configured the cloudhsm_client and mgmt_util before the HSM was active.

Thanks, Benton

**Comment by bentonstark** [comment]
Excellent!  Let me know if you run into any other issues.
