### ISSUE TITLE
Issue with using the Thales/Safenet Loggingshim

### ISSUE THREAD

**Issue by SaltySolomon** [bentonstark/pihsm#14]
Hello,

I am currently attempting to debugg a connection to the HSM, however when I try to use the logging shim the application fails to load the library:

ERROR: 'connect: failed to load shared library /usr/safenet/lunaclient/lib/libcklog2.so'

Is there an issue with the libary or am I doing something wrong, I think I have configured it correctly.

**Comment by bentonstark** [comment]
I can't say for sure.  The shared library libcklog2.so exports the PKCS-11 API.  More than likely there is something breaking in the libcklog2.so library that is resulting in the library to fail to load.  Have you attempted to load it using only SafeNet / Thales tooling?  This shim library does depend on configuration files to operate properly and it may also have binary dependencies that are failing to load.  https://thalesdocs.com/gphsm/luna/6.3/docs/network/Content/Utilities/cklog/cklog.htm

**Comment by SaltySolomon** [comment]
Thanks for the tip, it was an issue with my configuration, somehow there was a dropped .so missing.
