### ISSUE TITLE
Would an YubiHSM2 work?

### ISSUE THREAD

**Issue by gaia** [bentonstark/pihsm#6]
You probably haven't listed it bc you haven't tested it, but do you see a reason a [yubihsm 2](https://www.yubico.com/products/yubihsm/) would not work?

**Comment by bentonstark** [comment]
I have not tested the YubiHSM 2 with py-hsm. As long as the YubiHSM 2 has PKCS#11 compliant library it should work. I was unable to find any technical guides on the Yubico site to look at. The only code I know of for the YubiHSM 2 interfaces with the hardware using a proprietary API.  Annoyingly Yubico named their following python module pyhsm when it actually only interfaces with the YubiHSM 2.  Its the reason why I had to name my project py-hsm. 

https://github.com/Yubico/python-pyhsm/tree/master/pyhsm

**Comment by gaia** [comment]
Thanks. Maybe this will help? https://developers.yubico.com/YubiHSM2/Product_Overview/

**Comment by bentonstark** [comment]
So that definitely shows they support the PKCS#11 API version 2.40 which is good. The SDK will probably detail the specific calls supported such as C_Sign.
